# Generated by Django 4.1 on 2022-08-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("title",),
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
