# Generated by Django 4.1 on 2022-08-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="context",
        ),
        migrations.AddField(
            model_name="news",
            name="content",
            field=models.TextField(blank=True, max_length=255, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="news",
            name="published",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="news",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
    ]
